### ISSUE TITLE
Use Firefox for Local Tests

### ISSUE THREAD

**Issue by bethge** [jquery/PEP#349]
With Chrome supporting Pointer Events we should use a browser that does not support Pointer Events for local testing.
I switched to FF for the `NullTunnel` in the local Intern configuration file but had no luck:
FF opens but doesn't run anything, the tests on the command line just time out.

FF Version: 53.0.3
OS: macOS 10.12.4
Console dump:

```
Running "intern:pointerevents" (intern) task
Listening on 0.0.0.0:9000
Tunnel started
>> Suite firefox on any platform FAILED
UnknownError: [POST http://localhost:4444/wd/hub/session / {"desiredCapabilities":{"name":"tests/intern-local","idle-timeout":60,"browserName":"firefox"}}] Unable to connect to host localhost on port 7055 after 45000 ms. Firefox console output:
compat@mozilla.org.xpi
1496130193023	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1496130193025	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1496130193025	addons.manager	DEBUG	Provider finished startup: XPIProvider
1496130193026	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1496130193027	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1496130193027	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1496130193027	addons.manager	DEBUG	Starting provider: GMPProvider
1496130193031	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1496130193031	addons.manager	DEBUG	Provider finished startup: GMPProvider
1496130193031	addons.manager	DEBUG	Starting provider: PluginProvider
1496130193031	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1496130193032	addons.manager	DEBUG	Provider finished startup: PluginProvider
1496130193032	addons.manager	DEBUG	Completed startup sequence
1496130193326	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1496130193327	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1496130193327	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1496130193329	DeferredSave.extensions.json	DEBUG	Starting write
1496130193415	addons.repository	DEBUG	No addons.json found.
1496130193415	DeferredSave.addons.json	DEBUG	Save changes
1496130193418	DeferredSave.addons.json	DEBUG	Starting timer
1496130193432	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1496130193432	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1496130193432	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1496130193451	DeferredSave.extensions.json	DEBUG	Write succeeded
1496130193451	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 19
1496130193474	DeferredSave.addons.json	DEBUG	Starting write
1496130193481	DeferredSave.addons.json	DEBUG	Write succeeded
2017-05-30 09:43:13.985 firefox-bin[77466:656271] IMKInputSession presentFunctionRowItemTextInputViewWithEndpoint:completionHandler: : [self textInputContext]=0x128b67640 *NO* NSRemoteViewController to client, NSError=Error Domain=NSCocoaErrorDomain Code=4097 "connection from pid 0" UserInfo={NSDebugDescription=connection from pid 0}, com.apple.inputmethod.EmojiFunctionRowItem
2017-05-30 09:43:14.274 firefox-bin[77466:656271] IMKInputSession presentFunctionRowItemTextInputViewWithEndpoint:completionHandler: : [self textInputContext]=0x128b67640 *NO* NSRemoteViewController to client, NSError=Error Domain=NSCocoaErrorDomain Code=4097 "connection from pid 0" UserInfo={NSDebugDescription=connection from pid 0}, com.apple.inputmethod.EmojiFunctionRowItem
2017-05-30 09:43:14.689 plugin-container[77467:656700] * CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x8d3b, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-05-30 09:43:14.692 plugin-container[77467:656700] * CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x9003, name = 'com.apple.CFPasteboardClient'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-05-30 09:43:24.318 firefox-bin[77466:656271] IMKInputSession presentFunctionRowItemTextInputViewWithEndpoint:completionHandler: : [self textInputContext]=0x128b67640 *NO* NSRemoteViewController to client, NSError=Error Domain=NSCocoaErrorDomain Code=4097 "connection from pid 0" UserInfo={NSDebugDescription=connection from pid 0}, com.apple.inputmethod.EmojiFunctionRowItem
2017-05-30 09:43:24.411 firefox-bin[77466:656271] IMKInputSession presentFunctionRowItemTextInputViewWithEndpoint:completionHandler: : [self textInputContext]=0x128b67640 *NO* NSRemoteViewController to client, NSError=Error Domain=NSCocoaErrorDomain Code=4097 "connection from pid 0" UserInfo={NSDebugDescription=connection from pid 0}, com.apple.inputmethod.EmojiFunctionRowItem

  at Server.createSession  <node_modules/leadfoot/Server.js:362:15>
  at <node_modules/intern/lib/executors/Runner.js:198:23>
  at retry  <node_modules/intern/lib/util.js:818:13>
  at <node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/dojo/Promise.ts:11:11>
  at <node_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/dojo/Promise.ts:237:7>
  at <node_modules/dojo/nextTick.ts:44:3>
  at _combinedTickCallback  <internal/process/next_tick.js:73:7>
  at process._tickCallback  <internal/process/next_tick.js:104:9>

>> TOTAL: tested 0 platforms, 0/0 tests failed; fatal error occurred
```

**Comment by patrickhlauke** [comment]
**PEP has now [entered emeritus status at the OpenJS Foundation](https://openjsf.org/blog/2021/02/10/pointer-events-polyfill-pep-enters-emeritus-status-at-the-openjs-foundation/). This repository is now archived.**
